name: Subreddit Summaries

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'
          cache: 'pip' 
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pytest
        env: 
            IBM_API_KEY: ${{ secrets.IBM_API_KEY }}
            WATSONX_PROJECT_ID: ${{ secrets.WATSONX_PROJECT_ID }}
            IBM_CLOUD_URL: ${{ secrets.IBM_CLOUD_URL }}
            PRAW_CLIENT_SECRET: ${{ secrets.PRAW_CLIENT_SECRET }}
            PRAW_CLIENT_ID: ${{ secrets.PRAW_CLIENT_ID }}
            DB_PATH: ${{secrets.DB_PATH}}
            SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}
            FROM_EMAIL: ${{secrets.FROM_EMAIL}}
            TEMPLATE_ID: ${{secrets.TEMPLATE_ID}}
            CLOUDAMQP_URL: ${{secrets.CLOUDAMQP_URL}}
            PYTHONPATH: .
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
